<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lp  Xut Tuyn Dng</name>
   <tag></tag>
   <elementGuidId>0a9fbc9d-a0f0-4039-bfd4-d0001d12a90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-startcol']/div/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.containerListMy > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2502c680-b9e1-41f4-bbfd-8a1c59ab9fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.talentnetwork.vn/vi/admin/requisition/create</value>
      <webElementGuid>e01d5839-f469-4c33-8fbe-eb92bd82b21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lập Đề Xuất Tuyển Dụng</value>
      <webElementGuid>e0b70f15-57c2-4f74-be89-7f73c5275a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-startcol&quot;)/div[@class=&quot;wcommon&quot;]/div[@class=&quot;containerListMy&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>08533134-cca4-445a-aef1-c60172b6ccc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-startcol']/div/div[2]/ul/li/a</value>
      <webElementGuid>84856712-2b75-43ba-b7a2-f10f2360c1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lập Đề Xuất Tuyển Dụng')])[3]</value>
      <webElementGuid>2441db79-c88e-408f-bc68-d86d6e2151f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản Lý Tuyển Dụng'])[5]/following::a[1]</value>
      <webElementGuid>d0cff3d3-e7e3-487a-bd58-ee5a48da33b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản Lý Referral'])[1]/following::a[4]</value>
      <webElementGuid>b5fdecd8-cf31-4d4f-89bc-637a6b3a6d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(614)'])[1]/preceding::a[1]</value>
      <webElementGuid>a9682dae-ee2e-41ca-a599-be596fa85aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://demo.talentnetwork.vn/vi/admin/requisition/create')])[3]</value>
      <webElementGuid>02f368a3-5412-4fa2-ad71-e22ead7f0707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/ul/li/a</value>
      <webElementGuid>0868d8e1-0ffb-4989-a035-c1fcfa4e0d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.talentnetwork.vn/vi/admin/requisition/create' and (text() = 'Lập Đề Xuất Tuyển Dụng' or . = 'Lập Đề Xuất Tuyển Dụng')]</value>
      <webElementGuid>e629881b-0556-4473-afbc-f0ea30f048bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
