<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng tuyn</name>
   <tag></tag>
   <elementGuidId>7be41a02-f012-4189-9697-8d323015d28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.i-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/div[2]/div/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac8df21a-fcbb-462b-8e3c-0f8076ad99a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-active</value>
      <webElementGuid>c641b1d2-53e3-4947-aaf8-ad2e5ad10a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.talentnetwork.vn/vi/admin/requisition/create?requisition_id=275912&amp;tab=tab_PostJob&amp;view=1</value>
      <webElementGuid>c635608d-b5d0-41dd-a815-04ec3f0747a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng tuyển</value>
      <webElementGuid>63cbeb35-4342-455d-b32f-085d60910af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;RightPanel&quot;]/div[@class=&quot;ShowData tabstyle2 cb-createRequisition&quot;]/div[@class=&quot;containerData&quot;]/div[@class=&quot;detail_w_tab&quot;]/div[@class=&quot;funcAction&quot;]/div[@class=&quot;ListActive width_130&quot;]/ul[1]/li[1]/a[@class=&quot;i-active&quot;]</value>
      <webElementGuid>fb22d634-82f8-4b71-b52b-90db5a083726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>295b71a8-ba28-41cb-91c5-095b5649ed6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng tuyển')]</value>
      <webElementGuid>e648e63e-ab56-4d31-87c4-7190bd0f1fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thao Tác'])[1]/following::a[1]</value>
      <webElementGuid>c52f4374-34a3-4637-a36a-0be94bce60e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản Lý Tuyển Dụng > Xem Chi Tiết'])[1]/following::a[1]</value>
      <webElementGuid>7ca16c20-961f-4162-85dc-fa072703a0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sao chép'])[1]/preceding::a[1]</value>
      <webElementGuid>3ef22b9c-c79a-4b96-ae40-62be4e2ef5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chỉnh Sửa'])[1]/preceding::a[2]</value>
      <webElementGuid>37ee4e0f-b8aa-4be1-84c0-cf825ca495b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng tuyển']/parent::*</value>
      <webElementGuid>07cbe4c8-2399-43b8-9014-dc815b21db73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.talentnetwork.vn/vi/admin/requisition/create?requisition_id=275912&amp;tab=tab_PostJob&amp;view=1')]</value>
      <webElementGuid>644cc768-d772-4ad7-b3ac-34ee3debd052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>e3d96525-f34f-4fe2-bcfc-0b2a52b98cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.talentnetwork.vn/vi/admin/requisition/create?requisition_id=275912&amp;tab=tab_PostJob&amp;view=1' and (text() = 'Đăng tuyển' or . = 'Đăng tuyển')]</value>
      <webElementGuid>98871e57-80eb-4708-9104-c86703f5fb8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
