<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng nhp CB.vn</name>
   <tag></tag>
   <elementGuidId>b6073879-a013-4f21-a343-5dd37e556831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.loginLinkCB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-menu-links']/ul/li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbc01abf-6125-4dc8-9aed-0f292a7a8160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginLinkCB</value>
      <webElementGuid>e698e609-24ff-4255-9a86-c037374eb180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>3ff1176d-c307-4dab-9d70-0677ed9e95ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập CB.vn</value>
      <webElementGuid>0d48d944-f7ed-4649-a428-679676cc0cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-menu-links&quot;)/ul[1]/li[10]/a[@class=&quot;loginLinkCB&quot;]</value>
      <webElementGuid>c6b26e96-b05c-4060-b3fc-7c64d9425c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-menu-links']/ul/li[10]/a</value>
      <webElementGuid>03a62d45-2682-4a07-a583-24a2e0e4b540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng nhập CB.vn')]</value>
      <webElementGuid>1bd48417-8cbd-429d-bfbf-bb65d773523d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar'])[1]/following::a[1]</value>
      <webElementGuid>8a1473d5-765b-4e55-8454-b12dd1768e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công Cụ Quản Lý'])[1]/following::a[2]</value>
      <webElementGuid>a904b27f-b549-465d-8c41-efa7fe547502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[1]</value>
      <webElementGuid>df5823bd-99b5-44ae-bc66-bf0afa169960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hân Nguyễn HR'])[2]/preceding::a[4]</value>
      <webElementGuid>21755942-3408-476e-9806-9abd3636cdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng nhập CB.vn']/parent::*</value>
      <webElementGuid>a868d8e0-f876-494e-a736-1024e522fbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>af98f483-a651-49ed-a0f1-3a3e86e5cb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>e19e4f62-b9d3-4c00-abf2-c79f28448324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Đăng nhập CB.vn' or . = 'Đăng nhập CB.vn')]</value>
      <webElementGuid>d8fa972c-5134-4078-b959-663e3e434cec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
