<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng tuyn</name>
   <tag></tag>
   <elementGuidId>9777fe41-9981-42b7-abc8-290c30b2b158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/div[2]/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.i-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>767660f8-52fe-4f0e-8f76-60e8624fbdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i-active</value>
      <webElementGuid>ffe5c700-0377-4269-b64a-e17eaf73faec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.talentnetwork.vn/vi/admin/requisition/create?requisition_id=276289&amp;tab=tab_PostJob&amp;view=1</value>
      <webElementGuid>1a221ead-e59b-4bae-ae4f-5143262e9150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng tuyển</value>
      <webElementGuid>1cfbd6da-7cec-44ed-a5ae-427f5bf91382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;RightPanel&quot;]/div[@class=&quot;ShowData tabstyle2 cb-createRequisition&quot;]/div[@class=&quot;containerData&quot;]/div[@class=&quot;detail_w_tab&quot;]/div[@class=&quot;funcAction&quot;]/div[@class=&quot;ListActive width_130&quot;]/ul[1]/li[1]/a[@class=&quot;i-active&quot;]</value>
      <webElementGuid>db49260c-24c6-4e28-a54c-a4d69f7114d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>badfa7e0-0924-4083-be2a-d05d952cc884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng tuyển')]</value>
      <webElementGuid>ff0e89a0-d9a0-4050-b41b-8e00703b5a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thao Tác'])[1]/following::a[1]</value>
      <webElementGuid>ae80835f-8468-45be-90c6-4448de010021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quản Lý Tuyển Dụng > Xem Chi Tiết'])[1]/following::a[1]</value>
      <webElementGuid>28eda412-d1e7-4188-a3c3-3f2fc1363041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sao chép'])[1]/preceding::a[1]</value>
      <webElementGuid>de348c83-2fa7-40e8-92c5-3c5bf523e7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chỉnh Sửa'])[1]/preceding::a[2]</value>
      <webElementGuid>3b12ffc8-54f0-47a3-87f4-10afba09960b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng tuyển']/parent::*</value>
      <webElementGuid>ef75b80f-6279-4b73-bf54-0194fd14b962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.talentnetwork.vn/vi/admin/requisition/create?requisition_id=276289&amp;tab=tab_PostJob&amp;view=1')]</value>
      <webElementGuid>ccc225a2-6a77-4d44-869d-7fac8f2ab2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/ul/li/a</value>
      <webElementGuid>d07539db-d398-40ac-8f2d-4788a5743b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.talentnetwork.vn/vi/admin/requisition/create?requisition_id=276289&amp;tab=tab_PostJob&amp;view=1' and (text() = 'Đăng tuyển' or . = 'Đăng tuyển')]</value>
      <webElementGuid>924a3ee4-8ab3-4764-ad7a-60193f0c7dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
