<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_S Dng Vic Lm Mu C Sn Trong Th Vin</name>
   <tag></tag>
   <elementGuidId>b2a78822-8281-4544-a9a5-0f6d9f621265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmCreateJob']/div/div/div[5]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link_create</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c5a403f-cabc-4085-99ec-9784d0553f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_create</value>
      <webElementGuid>5d0130d2-05d5-4489-a1c6-359cbbfcf3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>26555697-281e-4368-bacc-4e48a9a98c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sử Dụng Việc Làm Mẫu Có Sẵn Trong Thư Viện</value>
      <webElementGuid>3389f1eb-4134-4554-8ac0-02d1ffa6f16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateJob&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;fl_left width_570 popbox&quot;]/a[@class=&quot;link_create&quot;]</value>
      <webElementGuid>d4e5a390-fbd4-471c-8f28-87fce97cb0c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[5]/div/a</value>
      <webElementGuid>219ff460-ca28-49ae-8d90-e2fb7ac9e9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sử Dụng Việc Làm Mẫu Có Sẵn Trong Thư Viện')]</value>
      <webElementGuid>a91f1614-7ba1-4c4a-a87e-531db3d89761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông Tin Tuyển Dụng'])[1]/following::a[1]</value>
      <webElementGuid>ac29be0e-c5db-43a9-a2c3-3ad9260b75b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)'])[7]/following::a[1]</value>
      <webElementGuid>7e05f333-b934-46ff-a3bd-0c53cd40bca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mã Công Việc'])[1]/preceding::a[1]</value>
      <webElementGuid>5580b919-6e02-4230-891b-b9dfe289a3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sử Dụng Việc Làm Mẫu Có Sẵn Trong Thư Viện']/parent::*</value>
      <webElementGuid>46fd3805-00b6-4cb0-8333-a3d0ce8c8cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[10]</value>
      <webElementGuid>f8fd8c06-a4fc-4ae0-8eee-85d8c54e6a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>93add91b-6f56-4c2d-b9b8-b49a6df6330f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Sử Dụng Việc Làm Mẫu Có Sẵn Trong Thư Viện' or . = 'Sử Dụng Việc Làm Mẫu Có Sẵn Trong Thư Viện')]</value>
      <webElementGuid>78074a53-24ae-4e76-b0c2-c87bc693ec06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
