<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thng Bo_fancybox-close</name>
   <tag></tag>
   <elementGuidId>506be6b8-de37-4655-9b58-64a32f64c7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='fancybox-close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fancybox-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da2b8816-e1ea-4c1e-8f85-ae6578430fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-close</value>
      <webElementGuid>39bd0c53-cdd6-4708-a3d1-b52ce1166881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-close&quot;)</value>
      <webElementGuid>aaafd1bb-b01a-4c15-a53c-2f1884f1238e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='fancybox-close']</value>
      <webElementGuid>d7737ff8-1479-48be-aef3-a304ee7a64a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-outer']/a</value>
      <webElementGuid>038fcc7e-c607-42c8-8dae-311153886f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/a</value>
      <webElementGuid>480b47ae-7f96-4301-94b6-f92dec04190d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'fancybox-close']</value>
      <webElementGuid>f5447ce4-4e12-4947-b232-315ba7de2378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
