<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thng Bo_fancybox-close</name>
   <tag></tag>
   <elementGuidId>6c5c0b9f-0a96-400c-99a6-c341a88461ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='fancybox-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2247b17b-b486-4079-86d4-203d2cdbad96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-close</value>
      <webElementGuid>5209af1b-ed09-4220-8c1c-b869c78d560d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-close&quot;)</value>
      <webElementGuid>eff9e06f-1915-4cc2-835f-71f098e7ba29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='fancybox-close']</value>
      <webElementGuid>598ec0d3-fd2c-4015-aa6b-b1458a9f4591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-outer']/a</value>
      <webElementGuid>021fd252-5a08-4cd8-a9b1-d14f3c7788a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/a</value>
      <webElementGuid>78e29754-8f93-41e5-8b44-a62a2cc84a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'fancybox-close']</value>
      <webElementGuid>2d4b5dd7-5d69-4846-8694-423dc33b4bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
