<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sa_fancybox-frame1656296652551</name>
   <tag></tag>
   <elementGuidId>46e05e73-8771-4b81-a7fb-ace1474951f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5beeab04-6d15-471b-aa18-4ca1ebe30fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame</value>
      <webElementGuid>d227b1c5-bca2-4e89-aae0-0a453e096d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1656296652551</value>
      <webElementGuid>ee3dc06f-1837-4905-9a28-067779d300ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>34bd13b6-cc66-45c3-9ad1-8d0eef95469f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d52e588-0956-4eda-8258-ceea41700b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4ba6bf84-d417-49ef-81fd-87405792eb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://careerbuilder.vn/vi/employers/hrcentral/ordertn?TID=QVBJX1RTX1RyYW5zYWN0aW9uVUlfMjcwNjIwMjJfMTY1MTJfMjc2Mjg5</value>
      <webElementGuid>8ffea289-16c3-43a8-b037-20b6e9b1e08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame&quot;)</value>
      <webElementGuid>483922fd-82e9-4d3b-b0e1-43782c7e11c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame']</value>
      <webElementGuid>228327af-23da-4728-bebc-0fd31455621f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-content']/iframe</value>
      <webElementGuid>b0fbd2e3-a26b-48c9-b079-943bb92e0c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/iframe</value>
      <webElementGuid>652475e6-9a7e-4659-8f3f-33ad68b017a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame' and @name = 'fancybox-frame1656296652551' and @src = 'https://careerbuilder.vn/vi/employers/hrcentral/ordertn?TID=QVBJX1RTX1RyYW5zYWN0aW9uVUlfMjcwNjIwMjJfMTY1MTJfMjc2Mjg5']</value>
      <webElementGuid>4dbdde91-cf85-45b2-bff4-721f4be6bc6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
