<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sa_fancybox-frame1655968287229</name>
   <tag></tag>
   <elementGuidId>da12def8-740e-48e5-99c3-32c852af1b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>53f9286c-0a89-43b6-bb1c-aae8da5eaa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame</value>
      <webElementGuid>06a3b759-bd33-4dcd-a561-02910a9b9fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1655968287229</value>
      <webElementGuid>e3cd9b95-55c1-4a78-96ee-e50e4303a987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e466f2c2-9e83-4d90-9a63-59c768886277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>45418f9b-8b3e-4823-861c-7e85c01276dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>aa2ff2f9-c85f-4cc5-9fea-3a6ee37470fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://careerbuilder.vn/vi/employers/hrcentral/ordertn?TID=QVBJX1RTX1RyYW5zYWN0aW9uVUlfMjMwNjIwMjJfMTY1MTJfMjc1OTEy</value>
      <webElementGuid>c38f6da9-b674-44ee-bd00-9ecf9880bbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame&quot;)</value>
      <webElementGuid>3b1e6fff-f314-40f3-a849-d36b51aa6c47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame']</value>
      <webElementGuid>22086116-c8f9-4c1c-8dd7-21ada82e5204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-content']/iframe</value>
      <webElementGuid>f55127af-a748-4c45-bbf2-08a42bae59c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/iframe</value>
      <webElementGuid>37ccf827-5ef4-441f-8bc0-b0adbe828be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame' and @name = 'fancybox-frame1655968287229' and @src = 'https://careerbuilder.vn/vi/employers/hrcentral/ordertn?TID=QVBJX1RTX1RyYW5zYWN0aW9uVUlfMjMwNjIwMjJfMTY1MTJfMjc1OTEy']</value>
      <webElementGuid>589eb9c3-691e-43ba-b08d-42391644e884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
