<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Talent Network_post_cb</name>
   <tag></tag>
   <elementGuidId>ed15bd1f-aaee-4ec9-89d7-1d10e52f4b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#post_cb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='post_cb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75aa72c6-dcdc-43c8-99b5-d23378a73616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44eafcec-b8e4-44ae-85d7-9d65ac3f7088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>post_cb</value>
      <webElementGuid>ed10f9bf-fc15-426b-b513-199e1a83e333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>post_cb</value>
      <webElementGuid>dd36e101-6eb0-459a-9da5-c4b6c9dd87d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ispublic</value>
      <webElementGuid>37b5e9f3-124b-4ae7-bf73-8136dfef1aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c28876e6-e56b-4fc3-ba72-5383870ad34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post_cb&quot;)</value>
      <webElementGuid>eb0d7e18-3f7c-4113-860f-60806d81e87b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='post_cb']</value>
      <webElementGuid>bdeff73a-49ee-4934-aca8-501621c44b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chk_post_cb']/span/label/input</value>
      <webElementGuid>da8517cf-c193-4aea-848a-bc05fe3dbe2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/span/label/input</value>
      <webElementGuid>96e92ad4-baf2-4a36-a3e2-2bcba3aeea7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'post_cb' and @id = 'post_cb']</value>
      <webElementGuid>415452e4-8cf8-4db2-8da0-8f3f4e73ba3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
