<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>e76903b4-8fa2-4748-9350-38695a512a1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Đăng Tuyển Dụng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7df4012c-6829-4020-b3cd-7eb3a801d444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58e334d3-d714-4374-a5f6-dbdec6373536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng Tuyển Dụng</value>
      <webElementGuid>bd09a0e9-9bcf-447b-b7f7-da73926fd985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>is_Filter_Form();</value>
      <webElementGuid>2b055a6a-5cad-4497-a050-580c62ca35d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;box_maincontent postOnline&quot;]/div[@class=&quot;clear SMTpostOnline&quot;]/div[@class=&quot;fl_left mar_right5 btnPostJob&quot;]/span[@class=&quot;btn_submit&quot;]/input[1]</value>
      <webElementGuid>d8b7a494-7a6c-41ba-9674-38e21079bbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostJob/Page_Cho mng bn n vi CareerBuilder Talent Network/iframe_Sa_fancybox-frame1656296652551</value>
      <webElementGuid>1cd7aac7-5e3f-4ca0-bf6c-1d89a2d6cd65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Đăng Tuyển Dụng']</value>
      <webElementGuid>b0672652-9ab1-4cf3-b887-6f461147236b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div[4]/div/span/input</value>
      <webElementGuid>b217a7f4-cee0-4ab4-8351-f76c3a4d9d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>3304bfe5-e0cc-4283-924c-350ae198b2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c40836a8-ea3d-4205-8114-2868b4f89448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
