<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ch ng_btnconfirm</name>
   <tag></tag>
   <elementGuidId>e195bb18-2ba2-43b2-8364-5eaaf869dd5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnOrderConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnOrderConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6552756-f5e6-4cc0-b3ae-a2b41425b4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>02d6caba-6c9c-453f-8cd4-6cdc427f1847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>XÁC NHẬN</value>
      <webElementGuid>a43db836-eeee-480c-ae35-f01aefc544ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnconfirm</value>
      <webElementGuid>700d4e8a-d0b4-4085-b640-d4af1254d050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnOrderConfirm</value>
      <webElementGuid>990c2958-c8ef-4ea3-a429-78c215b8e4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnOrderConfirm&quot;)</value>
      <webElementGuid>5b2714b0-7ec5-4270-a93e-2f935a4db8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostJob/Page_Cho mng bn n vi CareerBuilder Talent Network/iframe_Sa_fancybox-frame1656296652551</value>
      <webElementGuid>ecd982b9-db64-4fe3-8a26-a0187ceae74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnOrderConfirm']</value>
      <webElementGuid>36ffbcb1-3caf-4516-9c1c-694cbf2fff64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmOrderConfirm']/div[2]/div[3]/ul/li/span/input</value>
      <webElementGuid>8bb5de19-c6cb-43f9-9a25-e4aa13c61191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>fad696d7-5d6c-4c16-8132-29c55f47e08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnconfirm' and @id = 'btnOrderConfirm']</value>
      <webElementGuid>4c70c20d-34c9-4566-b0f1-e3140c38a969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
