<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_T_experience_from</name>
   <tag></tag>
   <elementGuidId>74f5e75a-392f-4f9a-b3e3-2ce053b21453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='experience_from']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#experience_from</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bcc1d53-5215-4b10-88fd-68ab0cb51bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_experience input_short numeric_only</value>
      <webElementGuid>61afe9df-f5a1-431b-9f19-5903ccf2b33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>experience_from</value>
      <webElementGuid>d728cb76-44b4-4b96-a0c0-57243e882505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>experience_from</value>
      <webElementGuid>81f6a6ec-1e3b-4eea-b511-564cc56cfbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>292d4e48-e688-4a8f-9c2c-0f71700212c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experience_from&quot;)</value>
      <webElementGuid>9bca0588-919d-4100-9b12-d00affef83f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='experience_from']</value>
      <webElementGuid>5cd7e430-90e3-48ed-a5f8-8ea5aab91878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[11]/div/div/input</value>
      <webElementGuid>4b441eb5-097d-464d-b0b9-45f3373b229d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>4796a7ab-1338-4b99-8570-d7c6d1aa2875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'experience_from' and @name = 'experience_from']</value>
      <webElementGuid>0b2d4d2f-135e-4fcd-b69c-f178a39c2a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
