<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ch ng_btnconfirm</name>
   <tag></tag>
   <elementGuidId>cc712aa1-1d96-4b5a-bc53-3ac602dbacd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnOrderConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnOrderConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fab8917-b570-44ea-823e-e58d221713aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2469744d-c53e-405d-b267-444693ab9d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>XÁC NHẬN</value>
      <webElementGuid>2a9c58a7-7562-42f8-ad87-abbf0dc342fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnconfirm</value>
      <webElementGuid>d80f4d5a-4995-4977-b55c-c9646265ab60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnOrderConfirm</value>
      <webElementGuid>17048ed7-50a0-4543-a5e4-bd026d5baf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnOrderConfirm&quot;)</value>
      <webElementGuid>12d5f547-3de9-41fe-9dbf-363bfdd9b5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostJob/Page_Cho mng bn n vi CareerBuilder Talent Network/iframe_Sa_fancybox-frame1655968287229</value>
      <webElementGuid>498b8db9-c391-4520-b2cf-b02573594b79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnOrderConfirm']</value>
      <webElementGuid>2a398537-b16d-4d35-b0a9-fdae3c5f4106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmOrderConfirm']/div[2]/div[3]/ul/li/span/input</value>
      <webElementGuid>f939588a-f119-4fe3-a84e-9b2effa50caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>48431a06-2396-4281-80c0-5061adb50520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnconfirm' and @id = 'btnOrderConfirm']</value>
      <webElementGuid>6d38580e-09a3-485f-a5b8-b34b629739cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
