<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S Dng Vic Lm Mu C Sn Trong Th Vin_btn_9a003c</name>
   <tag></tag>
   <elementGuidId>5ffd9407-20f0-4e96-9dce-ba5772bd155f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnSaveJoblib&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnSaveJoblib']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d0883b1-584c-4ffd-aca7-6e0bcc9fd300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb73be62-a83d-4b47-917a-5bf8e54323c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSaveJoblib</value>
      <webElementGuid>a64a201a-1763-49c6-a3dd-5497f0a8b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Chọn</value>
      <webElementGuid>0b73f324-e17c-4bfb-bed4-e1952bd991d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui_btnCb btnSmall mar_left5</value>
      <webElementGuid>ff6ab6cb-dfc3-4d6a-880d-48fe99e5db43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>chooseJobLibrary();</value>
      <webElementGuid>7f5c929c-6e2a-42c0-9698-9d9a394755e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateJob&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;fl_left width_570 popbox&quot;]/div[@class=&quot;themetips JobLibrary DataGot&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;ui_btnCb btnSmall mar_left5&quot;]</value>
      <webElementGuid>b23fb3c1-5e38-491c-a19d-84bae862c4b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnSaveJoblib']</value>
      <webElementGuid>5e98974c-0d8f-4cf9-b255-5859daea866c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>06aa6426-b04c-46c2-a12d-a1ced1a38a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>aae9908d-2c56-446b-ae87-6f0fa947ee67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSaveJoblib']</value>
      <webElementGuid>edcc0257-c964-4558-b1b7-bfab2445beb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
