<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__requiredate</name>
   <tag></tag>
   <elementGuidId>45d415bf-b2c9-4ca8-ab47-941bb0d07432</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requiredate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#requiredate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d21ca3f0-6a8d-4c40-8e09-f57cec456382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requiredate</value>
      <webElementGuid>98895c01-ded1-4acc-8c9d-1b6b86f840d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requiredate</value>
      <webElementGuid>c5bc2ab3-2312-4bb1-8908-c89949fef36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date_month required hasDatepicker error</value>
      <webElementGuid>8d4a4822-0cbf-4a54-b858-8ce9920546ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requiredate&quot;)</value>
      <webElementGuid>0e8f8e03-9040-49fa-a1d5-9f735edf4c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requiredate']</value>
      <webElementGuid>73083533-0d32-4b95-b072-a287e2b80a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[20]/fieldset/div[4]/div/input</value>
      <webElementGuid>2992122d-2354-4c41-931a-2e29e02b758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>198a1dad-de1e-418e-b537-ca4708155a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'requiredate' and @id = 'requiredate']</value>
      <webElementGuid>ce39588a-4ac5-45ca-b8ab-30036da09664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
