<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng tuyn dng trong 30 ngy_c_pack</name>
   <tag></tag>
   <elementGuidId>1509ea2f-2d70-48fe-82cb-69a22800eda4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c_pack_2338804_1000_3468185']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c_pack_2338804_1000_3468185</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>853ab41d-12ff-4a9f-8320-4c582e4d30de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>772b36b9-6201-4e3e-ae74-888bd7ef0696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c_pack</value>
      <webElementGuid>82a26268-d28a-43a7-aca8-f54c526130a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c_pack_2338804_1000_3468185</value>
      <webElementGuid>50e7a6a7-bcea-447f-8574-e1e3e86a5f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s_radio</value>
      <webElementGuid>c4ab145b-be4c-48c5-bad6-09b5af953e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2338804_1000_3468185</value>
      <webElementGuid>0dd6c3cb-7d4d-49ab-9bd5-7749513a3c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loadSubServices('35A4E900', 1000, 3468185);</value>
      <webElementGuid>8566d598-553f-4d75-b2a2-20f0611ae91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c_pack_2338804_1000_3468185&quot;)</value>
      <webElementGuid>decb0693-e968-4cc5-ae95-1732e2846485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostJob/Page_Cho mng bn n vi CareerBuilder Talent Network/iframe_Sa_fancybox-frame1656296652551</value>
      <webElementGuid>88054b9d-4dff-451b-abef-2cb3fb6b5bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c_pack_2338804_1000_3468185']</value>
      <webElementGuid>efddba1d-7d1a-457a-9552-cc6629e37d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//dd[@id='divpack_2338804_1000_3468185']/span/input</value>
      <webElementGuid>aff37606-e182-47dc-9220-39bd7bea1a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[8]/span/input</value>
      <webElementGuid>e4a872ea-d967-43bd-afc5-31f691c3ee4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'c_pack' and @id = 'c_pack_2338804_1000_3468185']</value>
      <webElementGuid>9e093a78-c1cb-4fc9-9b20-0a366853aa87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
