<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__requiredate</name>
   <tag></tag>
   <elementGuidId>356c3f3e-f461-4bdd-bad3-3ea8485965e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requiredate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requiredate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51a546ad-8a44-42b8-bc6f-7ea4ed63f3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requiredate</value>
      <webElementGuid>e8815ab6-30f7-4b82-9ec4-ec07377dfcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requiredate</value>
      <webElementGuid>d41d4ba9-3980-4a94-bf3f-91fdbdec8cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date_month required hasDatepicker error</value>
      <webElementGuid>3d14bcfb-f5cd-4218-9f79-e3bb680640a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requiredate&quot;)</value>
      <webElementGuid>fa5a3584-502d-489d-b41c-62ce831fcec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requiredate']</value>
      <webElementGuid>cd49252c-8988-42a8-b751-3217aea21a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[20]/fieldset/div[4]/div/input</value>
      <webElementGuid>ffd193a9-2606-4e87-b3e1-bfe50f05b9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>cecef9fc-7c9e-4681-9408-3ff3a796d42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'requiredate' and @id = 'requiredate']</value>
      <webElementGuid>8e66a572-2f2e-47fe-ab93-3a2b45f5370c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
