<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S Dng Vic Lm Mu C Sn Trong Th Vin_btn_9a003c</name>
   <tag></tag>
   <elementGuidId>d801ca40-d8f5-400d-bc70-682932f867e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnSaveJoblib']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnSaveJoblib&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fdaab48-9e6f-4e5c-90fc-a350c3e2d2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76443a90-37bc-4972-92d7-986bfd40f587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSaveJoblib</value>
      <webElementGuid>ff47df07-6171-45c0-a3ad-6b0e7a2c983d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Chọn</value>
      <webElementGuid>7205996a-86c4-416d-b7ca-e55ab74fa0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui_btnCb btnSmall mar_left5</value>
      <webElementGuid>5d4464e4-bd9f-44d0-bb32-07e0c570803a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>chooseJobLibrary();</value>
      <webElementGuid>7da36d35-3b8f-470c-ba29-47996c433e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateJob&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;fl_left width_570 popbox&quot;]/div[@class=&quot;themetips JobLibrary DataGot&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;ui_btnCb btnSmall mar_left5&quot;]</value>
      <webElementGuid>1ee1a47f-1e01-4b27-b45c-a428a31e8c55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnSaveJoblib']</value>
      <webElementGuid>16b0a859-8790-4adf-886f-207bf79b821b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>da128f54-d4a5-44ea-914a-883950f8623a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>448577dd-502d-485b-ac7f-36d96b4bcfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSaveJoblib']</value>
      <webElementGuid>a5a40c00-44df-4495-93f8-2651aa2ec428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
