<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_n_experience_to</name>
   <tag></tag>
   <elementGuidId>3348538f-5c34-4ddf-83f9-562bdabfed21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='experience_to']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#experience_to</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b887c54-4dcc-4e72-b236-630582cafbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt_experience input_short numeric_only</value>
      <webElementGuid>b1ba8ca0-14cb-4871-983e-8e23e734bf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>experience_to</value>
      <webElementGuid>3521dff6-cc06-4d77-a19b-fff1f2845363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>experience_to</value>
      <webElementGuid>b9da7dd9-4ace-4fed-8c3d-1bdaad9be36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b09814d1-5b9e-4966-8c7c-bf65cf56ba14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experience_to&quot;)</value>
      <webElementGuid>06417410-5962-47f5-9d6c-0f8a06e1ccd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='experience_to']</value>
      <webElementGuid>8a825b45-dac4-4756-ba3d-c2db7d0c0aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div[11]/div/div/input[2]</value>
      <webElementGuid>b68dabe7-a9aa-401a-8109-057955f7a58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input[2]</value>
      <webElementGuid>eed6ce7e-5d81-4860-808c-ecb1e71463ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'experience_to' and @name = 'experience_to']</value>
      <webElementGuid>5cc44db1-a0c7-4523-b359-9502b9fb6a79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
