<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work from home_ui_btnCb</name>
   <tag></tag>
   <elementGuidId>57a80c1e-3af9-4f18-82ef-32175cd4b43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmPostJob > div.form > div.row > input.ui_btnCb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad9d20ce-6ffa-447a-9678-c53eab686483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbaafd72-2d9c-44d9-9805-59d68acc26c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>08a29096-4a09-423a-b6d7-192f8f51ae3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui_btnCb</value>
      <webElementGuid>e6f9f2dc-116a-4549-87ba-d776ed257be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>actionPostTab(275912, 0)</value>
      <webElementGuid>ecd22dd9-1e9c-4866-964d-17492e259a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPostJob&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;ui_btnCb&quot;]</value>
      <webElementGuid>9e725883-2e0e-4d20-b8d0-96c354ab0e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>235a6ab4-a48e-436d-b8cd-40c412816056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPostJob']/div/div[11]/input</value>
      <webElementGuid>1cba8fa5-e12c-48de-9b21-14eb820435b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>2edf6c83-54cd-46c8-99b2-845cbfff5d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>5f3b2d73-1ab5-44be-8abd-db69d901b750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
