<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__job_expiredate</name>
   <tag></tag>
   <elementGuidId>3deb7555-98dc-4ea9-832e-727b23643831</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_expiredate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_expiredate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>926fd2eb-cc13-4b76-b378-6e36f281e326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_expiredate</value>
      <webElementGuid>58468400-4d0b-4f28-b7a2-1bb5af6715b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_expiredate</value>
      <webElementGuid>a3730f06-2ed9-4815-afc2-0cc50fb22c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date_month hasDatepicker</value>
      <webElementGuid>e6e6254d-61c1-4800-9cc4-b107eb6475d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_expiredate&quot;)</value>
      <webElementGuid>72a7cd52-41da-4267-9e5d-c91845ade0b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_expiredate']</value>
      <webElementGuid>10598f3a-ba74-488f-97e8-8e73dbed056a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPostJob']/div/div[2]/div/div/input</value>
      <webElementGuid>d1ed4a0b-d55e-49d1-8743-2ac54a01ed7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/input</value>
      <webElementGuid>db2505c9-3989-4537-b3f3-299ada6ee9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'job_expiredate' and @id = 'job_expiredate']</value>
      <webElementGuid>b7dbf6eb-30bf-44f7-9871-ff3b125a2f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
