<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>41cde89e-0428-4603-9436-5aa6709169d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Đăng Tuyển Dụng']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a561fe05-7779-4b9c-97a8-37fdf372afce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>abead685-ef64-4089-879e-23442f562716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng Tuyển Dụng</value>
      <webElementGuid>937b2486-13a0-4cb5-afee-750868f35d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>is_Filter_Form();</value>
      <webElementGuid>53340154-926a-4035-ab58-8ad0aa73187a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm&quot;)/div[@class=&quot;box_maincontent postOnline&quot;]/div[@class=&quot;clear SMTpostOnline&quot;]/div[@class=&quot;fl_left mar_right5 btnPostJob&quot;]/span[@class=&quot;btn_submit&quot;]/input[1]</value>
      <webElementGuid>d878c38c-1b0b-4842-ac56-9e5bd75b27d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostJob/Page_Cho mng bn n vi CareerBuilder Talent Network/iframe_Sa_fancybox-frame1655968287229</value>
      <webElementGuid>1c5e1a58-d2c9-4390-9a3a-8200d4f76f75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Đăng Tuyển Dụng']</value>
      <webElementGuid>985d9b14-778a-47a5-9191-131497a2e136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm']/div/div[4]/div/span/input</value>
      <webElementGuid>25b65e7c-5b90-4a81-b91d-0d321057b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>a017cf88-ee98-4cb8-b4f1-7332228fef80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>9d6de5bc-883a-4d61-8e0b-d27c4f8fd843</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
