<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hn Nguyn HR (han.nguyenmail.careerbuilder.vn)</name>
   <tag></tag>
   <elementGuidId>046b5f44-63cf-470a-bb34-9d5335c63601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmCreateJob']/div/div/div/div/div/div/ul/li[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dffe5f36-bba7-4d26-bd2b-060460d0c0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>ef5b2028-9032-42a9-bf5e-57743d9e90c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>d76199bc-525e-4435-93ca-e097a3487c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)</value>
      <webElementGuid>22acf0ff-1f81-4ef6-8719-ecfbbaba0f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateJob&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;fl_left width_570&quot;]/div[@class=&quot;chosen-container chosen-container-single chosen-container-active&quot;]/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>e67404ab-e577-4b70-b49a-a665f5f89772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div/div/div/div/ul/li[19]</value>
      <webElementGuid>cbb637a5-12e1-44ac-8462-fa4eef99e414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vũ Đoàn (vu.doan@mail.careerbuilder.vn)'])[2]/following::li[1]</value>
      <webElementGuid>6d8ceb0d-4ca1-49b7-9ccb-6e256316292c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lê Hoành (hoanhlotte@gmail.com)'])[2]/following::li[2]</value>
      <webElementGuid>3572e754-4e93-44d1-926b-b32952c69209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thuan Dinh (huy.tran@mail.careerbuilder.vn)'])[2]/preceding::li[1]</value>
      <webElementGuid>006845b3-003a-4028-81f6-bd872c6da2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trưởng Bộ Phận'])[1]/preceding::li[2]</value>
      <webElementGuid>07224e0f-b237-4913-840a-0ce6e099868a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]</value>
      <webElementGuid>47d92452-aa3c-4e47-b318-eb968cc6fa98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)' or . = 'Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)')]</value>
      <webElementGuid>7f7a3709-e5ca-4a1b-8c05-e34a77a55a5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
