<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Hn Nguyn HR (han.nguyenmail.careerbuilder.vn)</name>
   <tag></tag>
   <elementGuidId>04df599b-63e8-41f3-9fb4-3fe5bafcee6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmCreateJob']/div/div/div/div/div/div/ul/li[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a3dcf5b5-b91b-4986-be45-a9a202b30225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result</value>
      <webElementGuid>d543e163-587a-43eb-8063-d8b1d4d6477a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>36d7ac08-8415-487a-9319-16adae0d3297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)</value>
      <webElementGuid>4b566359-7ae1-44dd-bf27-935218a64c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateJob&quot;)/div[@class=&quot;form&quot;]/div[@class=&quot;clear&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;fl_left width_570&quot;]/div[@class=&quot;chosen-container chosen-container-single chosen-container-active&quot;]/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result&quot;]</value>
      <webElementGuid>ae914314-843d-4dcf-8423-3b69fdad4158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmCreateJob']/div/div/div/div/div/div/ul/li[19]</value>
      <webElementGuid>e058987f-927c-479b-a8ed-042dc65207d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vũ Đoàn (vu.doan@mail.careerbuilder.vn)'])[2]/following::li[1]</value>
      <webElementGuid>843f4fcc-d499-4e6c-a1bf-b848ebcc5c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lê Hoành (hoanhlotte@gmail.com)'])[2]/following::li[2]</value>
      <webElementGuid>e863c88e-3844-4042-a162-f670acf6ed27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thuan Dinh (huy.tran@mail.careerbuilder.vn)'])[2]/preceding::li[1]</value>
      <webElementGuid>de4db647-94e6-40ea-b815-2225d485fd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trưởng Bộ Phận'])[1]/preceding::li[2]</value>
      <webElementGuid>1344869c-e37a-4537-bfda-3974e131a71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[19]</value>
      <webElementGuid>39f4e4e5-cabc-4528-ab39-6e29c9513d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)' or . = 'Hân Nguyễn HR (han.nguyen@mail.careerbuilder.vn)')]</value>
      <webElementGuid>aed28bdd-3689-4ab4-8efd-58532b2aeee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
