<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_FAQ_fa fa-bars</name>
   <tag></tag>
   <elementGuidId>c93c6715-b062-45c3-8f99-ac5f90893866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-bars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show-menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa907bca-7574-4165-a5d3-0f786539d9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bars</value>
      <webElementGuid>e478751e-2306-4ffb-bf16-1da04d5cc7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-menu&quot;)/span[@class=&quot;fa fa-bars&quot;]</value>
      <webElementGuid>e3bdf395-528a-492a-a16e-c5a5b4457526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-menu']/span</value>
      <webElementGuid>18c8015b-bff8-4996-bfa9-5c29603f009a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>520cf613-8653-4d90-a128-78f011a65ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
