<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__submit</name>
   <tag></tag>
   <elementGuidId>25b24903-6d03-4d93-9724-f5a9197cfa98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Enter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73308f28-5d70-4976-a2f6-f9c3cf3d5cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>97541acd-a7e4-4064-a3a2-b16933dd0fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>e64bf4eb-a2bc-4aa4-8989-910bb44a7a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>92797733-4b9e-4720-8cc6-029db1e24fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_container&quot;)/div[@class=&quot;login_cont&quot;]/div[@class=&quot;login_box&quot;]/form[1]/p[@class=&quot;pad&quot;]/input[@class=&quot;submit&quot;]</value>
      <webElementGuid>3d3a4eac-88ee-4aaa-b79f-a741b1b63345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Enter']</value>
      <webElementGuid>fe3fb505-e862-45c5-ab02-b6402edc3b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_container']/div[5]/div/form/p[3]/input</value>
      <webElementGuid>1f5a3766-b2c7-4bc2-be64-2c8598df5c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>f688466d-ccf6-44ec-90d9-8f7b2a301af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>fd1d141e-bc72-4e83-8fd7-f2b46dd71042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
