<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Employers</name>
   <tag></tag>
   <elementGuidId>0a78d380-9794-4b84-b6ca-24846f8e74cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='yui-gen1']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>680f0545-4c23-441e-86f1-f60b6ce182ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://admin.talentnetwork.vn/rw/</value>
      <webElementGuid>92b8f4b4-b2eb-4226-91c3-9fee1e85ff91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> hassubmenu  selected</value>
      <webElementGuid>6d6e22a4-862a-4b12-a1bd-fcf532dca4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employers</value>
      <webElementGuid>9dde9972-44fe-4ede-b65a-6c14555e5750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui-gen1&quot;)/a[@class=&quot;hassubmenu  selected&quot;]</value>
      <webElementGuid>3a5d98dc-1126-4093-885f-c413686c6cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='yui-gen1']/a</value>
      <webElementGuid>91e4f97d-f618-458b-a9d0-d468eb494372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employers')]</value>
      <webElementGuid>b4fb59ed-6eba-43a1-a58c-96387f9bed6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home page'])[1]/following::a[1]</value>
      <webElementGuid>417b3558-cb01-45fd-9832-ef0c2f5fcd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::a[2]</value>
      <webElementGuid>ddc2de99-29f4-49df-9024-452cf758daff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Talent Network'])[1]/preceding::a[1]</value>
      <webElementGuid>fbfa45f5-033a-4c5f-bd15-550a93fde1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employers']/parent::*</value>
      <webElementGuid>d72941aa-49cc-40e7-9d46-a01b643f062a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://admin.talentnetwork.vn/rw/']</value>
      <webElementGuid>68738688-f9c3-4e8c-8544-c02fb501e3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>73fb7693-6fa5-4e65-8376-c9d3ecef7666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://admin.talentnetwork.vn/rw/' and (text() = 'Employers' or . = 'Employers')]</value>
      <webElementGuid>6fa98034-94fd-45f7-8565-4568362eaaa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
