<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Emp Name, Emp Email, Onwer)_keyword</name>
   <tag></tag>
   <elementGuidId>7f075282-0781-4ed8-99a2-56bbe12bc726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_keyword_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_keyword_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddfaea37-e949-49ea-b1d8-4d6d9402b6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36e31353-9a2e-4bb6-b603-10004dab446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>57c7dbc6-975d-4fe2-9fe0-3b964b3d8228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>b1610d1e-9459-4ad7-a176-43e3d726114a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_keyword_1</value>
      <webElementGuid>63d0d36e-c65e-419e-9808-7158bcdd9ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_keyword_1&quot;)</value>
      <webElementGuid>e5480873-c501-4b6f-9899-fd56cf0e11c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_keyword_1']</value>
      <webElementGuid>6ca3044f-a46f-4dde-819f-e6ab56012edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/form/table/tbody/tr/td[4]/input</value>
      <webElementGuid>f10715b1-e7ff-4e0f-8463-c6c5da81d867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>f74c157d-7c65-4cae-80d4-23a42439ebe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'keyword' and @id = 'id_keyword_1']</value>
      <webElementGuid>b5347304-9de4-411f-a862-3b1f17f04c91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
