<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keyword_chkSearchBy</name>
   <tag></tag>
   <elementGuidId>b3e7e881-63e2-40f5-8a1c-acd633baccf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='chkSearchBy'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0270c546-fe1d-4588-8984-c45acee5fc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ab5abd9f-fc8d-48eb-8de0-21a3c0d0787d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSearchBy</value>
      <webElementGuid>966533d8-536f-49a2-857c-c89c09bcf845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0b0fd613-1a94-4ce6-ba32-8484fb25a990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:choiceOption(this.value)</value>
      <webElementGuid>c8223668-4f27-4d8c-aa2b-96fd44586159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab3&quot;)/form[1]/table[1]/tbody[1]/tr[1]/td[3]/input[1]</value>
      <webElementGuid>5c65e225-b890-40ab-9d48-c1ee6155e5d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='chkSearchBy'])[2]</value>
      <webElementGuid>d6a278ae-4c5e-4137-bec5-70d384da109f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/form/table/tbody/tr/td[3]/input</value>
      <webElementGuid>2c9fbdd4-2c5c-4255-84f3-737403f31de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>586abfe2-a67b-4a9d-a5dd-1f2e7b740e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'chkSearchBy']</value>
      <webElementGuid>69155a78-3d0d-434f-ba1a-713d9f3f5e1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
