<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Implementer_btnSearch</name>
   <tag></tag>
   <elementGuidId>cc6d8725-dd03-4df5-abb2-a3fc4396d62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='btnSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;btnSearch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d18a82c-25d7-46c7-8a3a-8e970451d5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>20c91270-e9c8-400f-81ae-748005f217f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSearch</value>
      <webElementGuid>a36725fd-9b0b-4875-85c3-29907e648b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Filter </value>
      <webElementGuid>c0b30db6-2742-4f0b-a09f-1c06b1e1a481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab3&quot;)/form[1]/table[1]/tbody[1]/tr[5]/td[3]/input[1]</value>
      <webElementGuid>00b41ca5-e144-495d-a1b8-8187b8766f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='btnSearch']</value>
      <webElementGuid>9b830dc8-baf2-4fda-8166-d7de4149acf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/form/table/tbody/tr[5]/td[3]/input</value>
      <webElementGuid>5a944af9-bcd6-49ff-b120-7904f46c6ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/input</value>
      <webElementGuid>3544a1fc-a5c0-4278-a8e1-bc26261693da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnSearch']</value>
      <webElementGuid>df568325-f960-4e9f-9812-8e72d14332d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
